### ISSUE TITLE
Usage of `when`

### ISSUE THREAD

**Issue by bard** [hjkcai/typesafe-joi#12]
I'm trying the shiny 2.0.0-alpha and I might have found a bug:

```js
const sample = joi.object({
  cacheType: joi.string().valid('db', 'memory'),
  db: joi.object({
    url: joi.string(),
    databaseName: joi.string()
  }).required()
    .when('cacheType', {
      is: 'db',
      then: {
        url: joi.string().required(),
        databaseName: joi.string().required()
      },
      otherwise: {
        url: joi.string().forbidden()
          .error(new Error('DB_URL provided but CACHE_TYPE is not "db'))
      }
    })
})

const config = joi.attempt({
  cacheType: 'db',
  db: { url: 'http://localhost:1234', databaseName: 'test' }
}, schema)
```

Above, I want to require the presence of `config.db.url` and `config.db.databaseName` if `config.cacheType` is `db`, and forbid it otherwise. However tsc says:

```
Property 'db' does not exist on type 'ObjectSchema<Value<Record<any, any>, 
fromSchemaMap<{ cacheType: StringSchema<Value<never, never, "memory" | "db", 
undefined, false>>; db: AlternativesSchema<Value<Record<any, any>, never, never,
undefined, false>>; }>, never, undefined, false>>'. [2339]
```

(This wasn't working with 1.0 either, but placing a `// @ts-ignore` above `when()` made it work.)

**Comment by hjkcai** [comment]
Thanks. I am not very sure about the implementation of `when` (and it is REALLY complicated). I will try to find it out

**Comment by bard** [comment]
Me, I'd be happy with `when()` not narrowing the type at all, a type no-op so to speak, as long as it doesn't throw it away.

**Comment by hjkcai** [comment]
Sorry but I cannot reproduce this issue. I am using the code below:

```typescript
import * as joi from 'typesafe-joi'

const schema = joi.object({
  cacheType: joi.string().valid('db', 'memory'),
  db: joi.object({
    url: joi.string(),
    databaseName: joi.string()
  }).required()
    .when('cacheType', {
      is: 'db',
      then: {
        url: joi.string().required(),
        databaseName: joi.string().required()
      },
      otherwise: {
        url: joi.string().forbidden()
          .error(new Error('DB_URL provided but CACHE_TYPE is not "db'))
      }
    })
})

const config = joi.attempt({
  cacheType: 'db',
  db: { url: 'http://localhost:1234', databaseName: 'test' }
}, schema)
```

The type of `config` is:

```typescript
type config = ({} & {
    db?: ({} & {
        url?: string | undefined;
        databaseName?: string | undefined;
    }) | undefined;
    cacheType?: "db" | "memory" | undefined;
}) | undefined

// equivalent to
interface config {
  cacheType?: 'db' | 'memory',
  db?: {
    url?: string,
    databaseName?: string
  }
}
```

Could you please provide the complete code? And what is your TypeScript version?

**Comment by hjkcai** [comment]
However `db` should be required but it is optional here. This is obviously a bug.

**Comment by bard** [comment]
It might have been partly due to TypeScript 3.3.3. I upgraded to 3.4.5.

Code:

```js
import joi from 'typesafe-joi'

const schema = joi.object({
  cacheType: joi.string().valid('db', 'memory'),
  db: joi.object({
    url: joi.string(),
    databaseName: joi.string(),
  }).and('url', 'databaseName').required()
    .when('cacheType', {
      is: 'db',
      then: { url: joi.string().required() },
      otherwise: {
        url: joi.string().forbidden()
          .error(new Error('DB_URL provided but CACHE_TYPE is not "db"'))
      }
    })
}).required()

const config = joi.attempt({
  cacheType: 'db',
  db: { url: 'http://localhost:1234', databaseName: 'test' }
}, schema)
```

Reported type of `config.db`:

```js
(property) db?: ({} & {
  url?: string | undefined
  databaseName?: string | undefined
}) | undefined
```

That looks alright except for the `| undefined`. I suppose that's also why I don't get any completions when cursor is at `config.db.|`, whereas I do when typing `config!.db!.|`.

**Comment by hjkcai** [comment]
The extra `undefined` type will be gone in 2.0.0-alpha7. Please upgrade typesafe-joi and have a try.

**Comment by bard** [comment]
Works fine for me! `config.db` is no longer `| undefined`. :+1:
